import { Obra, ReactVideo } from './types.js';

export const OBRAS_INICIAIS: Obra[] = [
  {
    id: 'marvel',
    titulo: 'Marvel',
    tipo: 'filme',
    ano: 2024,
    generos: ['Ação', 'Heróis'],
    sinopse: 'Todos os reacts relacionados à franquia Marvel.',
    banner: 'https://images.unsplash.com/photo-1612036782180-6f0b6ce846ce?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1612036782180-6f0b6ce846ce?q=80&w=600&auto=format&fit=crop',
    trailerUrl: ''
  },
  {
    id: 'harry-potter',
    titulo: 'Harry Potter',
    tipo: 'filme',
    ano: 2024,
    generos: ['Fantasia', 'Magia'],
    sinopse: 'Reacts da franquia Harry Potter.',
    banner: 'https://images.unsplash.com/photo-1618944913480-b67ee16d7b77?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1618944913480-b67ee16d7b77?q=80&w=600&auto=format&fit=crop',
    trailerUrl: ''
  },
  {
    id: 'gta',
    titulo: 'GTA',
    tipo: 'jogo',
    ano: 2024,
    generos: ['Ação', 'Mundo Aberto'],
    sinopse: 'Reacts da franquia Grand Theft Auto.',
    banner: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=600&auto=format&fit=crop',
    trailerUrl: ''
  },
  {
    id: 'one-piece',
    titulo: 'One Piece',
    tipo: 'anime',
    ano: 2024,
    generos: ['Aventura', 'Ação'],
    sinopse: 'Reacts do anime One Piece.',
    banner: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600&auto=format&fit=crop',
    trailerUrl: ''
  },
  {
    id: 'the-last-of-us',
    titulo: 'The Last of Us',
    tipo: 'jogo',
    ano: 2024,
    generos: ['Ação', 'Terror'],
    sinopse: 'Reacts de The Last of Us.',
    banner: 'https://images.unsplash.com/photo-1542362567-b07e54358753?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1542362567-b07e54358753?q=80&w=600&auto=format&fit=crop',
    trailerUrl: ''
  },
  {
    id: 'isabela-roza-canal',
    titulo: 'Canal Isabela Roza',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Canal Isabela Roza (@roza_isa). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Canal Isabela Roza (@roza_isa). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@roza_isa',
    destacado: false,
    channelId: 'UChE_9ojxxGFFt9VH-huU-tg'
  },
  {
    id: 'janela-da-rua-canal',
    titulo: 'Janela da Rua',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Janela da Rua (@janeladarua). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Janela da Rua (@janeladarua). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@janeladarua',
    destacado: false,
    channelId: 'UC3GB6W8SyUw6IAhSuqULdGw'
  },
  {
    id: 'gamer-bisonho-canal',
    titulo: 'Gamer Bisonho',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Gamer Bisonho (@gamerbisonho). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Gamer Bisonho (@gamerbisonho). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@gamerbisonho',
    destacado: false,
    channelId: 'UCfgXcrb259iYPMBT5XRWYZg'
  },
  {
    id: 'jacy-mochizuki-react-canal',
    titulo: 'Jacy Mochizuki React',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Jacy Mochizuki React (@jacymochizukireact). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Jacy Mochizuki React (@jacymochizukireact). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@jacymochizukireact',
    destacado: false,
    channelId: 'UCCSlOUa8TVmOspfJV0LNdLA'
  },
  {
    id: 'sim-sou-lives-canal',
    titulo: 'Sim Sou Lives',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Sim Sou Lives (@simsoulives). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Sim Sou Lives (@simsoulives). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@simsoulives',
    destacado: false,
    channelId: 'UC9sap-rgC1rucGCjy4LqhAg'
  },
  {
    id: 'carol-e-rhay-canal',
    titulo: 'Carol e Rhay',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Carol e Rhay (@carolerhay). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Carol e Rhay (@carolerhay). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@carolerhay',
    destacado: false,
    channelId: 'UCoU_HlrAolc5sqhlPMZ_T0A'
  },
  {
    id: 'nat-e-vic-mv-canal',
    titulo: 'Nat e Vic MV',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Nat e Vic MV (@natevicmv). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Nat e Vic MV (@natevicmv). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@natevicmv',
    destacado: false,
    channelId: 'UCjDI6bXlnuAeS8KT8XXn8MA'
  },
  {
    id: 'biana-clips-canal',
    titulo: 'BIANA CLIPS',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal BIANA CLIPS (@bianaclips). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal BIANA CLIPS (@bianaclips). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@bianaclips',
    destacado: false,
    channelId: 'UCcfzPqK578MhiE2hA_qJZEg'
  },
  {
    id: 'mah-moojen-canal',
    titulo: 'Mah Moojen',
    tipo: 'canal',
    ano: 2026,
    generos: ['Reacts', 'YouTube'],
    synopsis: 'Categoria exclusiva para os reacts do canal Mah Moojen (@mahmoojenlives). Assista e acompanhe todas as reações maravilhosas deste canal!',
    sinopse: 'Categoria exclusiva para os reacts do canal Mah Moojen (@mahmoojenlives). Assista e acompanhe todas as reações maravilhosas deste canal!',
    banner: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1600&auto=format&fit=crop',
    poster: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?q=80&w=600&auto=format&fit=crop',
    trailerUrl: 'https://www.youtube.com/@mahmoojenlives',
    destacado: false,
    channelId: 'UCdfAq743YxDtyj1O5GrtO9w'
  },
];

export const VIDEOS_INICIAIS: ReactVideo[] = [];

export const CATEGORIAS_LISTA = [
  { id: 'alta', nome: 'Reacts em Alta' },
  { id: 'lancamentos', nome: 'Lançamentos' },
  { id: 'filmes', nome: 'Filmes' },
  { id: 'series', nome: 'Séries' },
  { id: 'jogos', nome: 'Jogos' },
  { id: 'animes', nome: 'Animes' },
  { id: 'terror', nome: 'Terror' },
  { id: 'acao', nome: 'Ação' },
  { id: 'comedia', nome: 'Comédia' },
  { id: 'ficcao', nome: 'Ficção' },
  { id: 'mais-assistidos', nome: 'Mais Assistidos da Semana' },
  { id: 'novos', nome: 'Novos Reacts' }
];
